plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        client_1 {
            client()
            ideName = "Client 1"
            gameDirectory = project.layout.projectDirectory.dir('runs/client_1')
            programArguments.addAll "--username", "Dev1"
        }
        client_2 {
            client()
            ideName = "Client 2"
            gameDirectory = project.layout.projectDirectory.dir('runs/client_2')
            programArguments.addAll "--username", "Dev2"
        }
        client_3 {
            client()
            ideName = "Client 3"
            gameDirectory = project.layout.projectDirectory.dir('runs/client_3')
            programArguments.addAll "--username", "Dev3"
        }
        data {
            data()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }